#learning exception handling for python

try:
  print(x)
except:
  print("An exception occured")
